const demoAccounts={'manager@vertexconsulting.com':{password:'workpilot',name:'Manasi Mehta',role:'Manager',title:'Administrator'},'employee@vertexconsulting.com':{password:'workpilot',name:'Rahul Sharma',role:'Employee',title:'Sales Team'}};
const seedTickets=[{id:'TASK-104',title:'Prepare monthly sales report',person:'Rahul Sharma',initials:'RS',priority:'High',due:'Today',date:'08 Sep',status:'In Progress',progress:65},{id:'TASK-098',title:'Client onboarding data review',person:'Priya Patel',initials:'PP',priority:'Critical',due:'2 days overdue',date:'06 Sep',status:'Overdue',progress:40},{id:'TASK-107',title:'Q3 dashboard performance audit',person:'Jordan Lee',initials:'JL',priority:'Medium',due:'Tomorrow',date:'09 Sep',status:'Assigned',progress:0},{id:'TASK-102',title:'Update product launch brief',person:'Ananya Rao',initials:'AR',priority:'High',due:'12 Sep',date:'12 Sep',status:'Pending Review',progress:90},{id:'TASK-101',title:'Consolidate vendor invoices',person:'Rahul Sharma',initials:'RS',priority:'Low',due:'15 Sep',date:'15 Sep',status:'Open',progress:10},{id:'TASK-095',title:'Website accessibility fixes',person:'Jordan Lee',initials:'JL',priority:'Medium',due:'Completed',date:'05 Sep',status:'Completed',progress:100}];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),statusClass=s=>'status-'+s.toLowerCase().replaceAll(' ','-'),initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
let tickets=JSON.parse(localStorage.getItem('workpilot-tickets')||'null')||seedTickets,currentUser=null,showingMine=false;
const accounts=()=>({...demoAccounts,...JSON.parse(localStorage.getItem('workpilot-accounts')||'{}')});
function save(){localStorage.setItem('workpilot-tickets',JSON.stringify(tickets));}function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function activateUser(user){currentUser=user;document.body.className='auth-ready';$('#profileName').textContent=user.name;$('#profileRole').textContent=user.title;$('#roleSwitch').innerHTML=`Viewing as <strong>${user.role}</strong>⌄`;$('#pageTitle').innerHTML=`Good morning, ${user.name.split(' ')[0]} <span>✦</span>`;$('#newTicket').style.display=user.role==='Employee'?'none':'';}
function row(t){return `<tr><td><button class="ticket-link" data-open="${t.id}"><strong>${t.id}</strong><small>${t.title}</small></button></td><td><div class="assignee"><span class="avatar">${t.initials}</span>${t.person}</div></td><td><span class="priority ${t.priority}">${t.priority}</span></td><td>${t.date}<small>${t.due}</small></td><td><button class="pill ${statusClass(t.status)} status-button" data-status="${t.id}" title="Click to advance status">${t.status}</button></td><td><span class="bar"><i style="width:${t.progress}%"></i></span>${t.progress}%</td><td class="more">•••</td></tr>`}
function filtered(){let q=$('#search')?.value.toLowerCase()||'',s=$('#statusFilter')?.value||'all',p=$('#priorityFilter')?.value||'all';return tickets.filter(t=>(!showingMine||t.person===currentUser?.name)&&(s==='all'||t.status===s)&&(p==='all'||t.priority===p)&&Object.values(t).join(' ').toLowerCase().includes(q))}
function renderRows(){let list=filtered();$('#priorityRows').innerHTML=(showingMine?list:tickets).slice(0,4).map(row).join('');$('#allRows').innerHTML=list.map(row).join('')||'<tr><td colspan="7" class="no-results">No tickets match these filters.</td></tr>';$('#ticketCount').textContent=tickets.length}
function renderDeadlines(){let due=tickets.filter(t=>['Today','Tomorrow','2 days overdue'].includes(t.due));$('#deadlineList').innerHTML=due.map(t=>`<div class="deadline"><div class="date-box"><span>SEP</span><b>${t.date.split(' ')[0]}</b></div><div><h3>${t.title}</h3><p>${t.id} · ${t.person}</p></div><span class="pill ${statusClass(t.status)} tag">${t.due}</span></div>`).join('')||'<p class="no-results">No urgent deadlines.</p>'}
function renderBoard(){let groups=['Open','Assigned','In Progress','Pending Review'];$('#kanban').innerHTML=groups.map(g=>{let a=tickets.filter(t=>t.status===g);return `<div class="board-column"><div class="board-title"><span>${g.toUpperCase()}</span><b>${a.length}</b></div>${a.map(t=>`<article class="kanban-card" data-open="${t.id}"><span class="priority ${t.priority}">${t.priority}</span><h3>${t.title}</h3><small>${t.id}</small><footer><span class="avatar">${t.initials}</span><span>◷ ${t.date}</span></footer></article>`).join('')||'<p class="no-results">No tickets</p>'}</div>`}).join('')}
function renderTeam(){let team=[['Rahul Sharma','RS','Sales','5 tickets','80%'],['Priya Patel','PP','Operations','4 tickets','75%'],['Jordan Lee','JL','Engineering','6 tickets','83%'],['Ananya Rao','AR','Marketing','3 tickets','100%']];$('#teamList').innerHTML='<div class="team-row header-row"><span>Member</span><span>Active workload</span><span>Completed</span><span>Completion rate</span></div>'+team.map(x=>`<div class="team-row"><div class="member"><span class="avatar">${x[1]}</span><div><strong>${x[0]}</strong><small>${x[2]}</small></div></div><span>${x[3]}</span><span>${Math.ceil(+x[3][0]/2)} this month</span><span class="completion">${x[4]}</span></div>`).join('')}
function render(){renderRows();renderDeadlines();renderBoard();renderTeam()}function advance(id){let t=tickets.find(x=>x.id===id),a=['Open','Assigned','In Progress','Pending Review','Completed'],i=a.indexOf(t.status);t.status=a[(i+1)%a.length];if(t.status==='Completed')t.progress=100;else if(!t.progress)t.progress=20;save();render();toast(`${t.id} moved to ${t.status}.`)}
$('#loginForm').onsubmit=e=>{e.preventDefault();let email=$('#loginEmail').value.trim().toLowerCase(),a=accounts()[email];if(!a||a.password!==$('#loginPassword').value){$('#loginError').textContent='That email or password does not match our records.';return}sessionStorage.setItem('workpilot-user',email);activateUser(a)};
$('#signupForm').onsubmit=e=>{e.preventDefault();let email=$('#signupEmail').value.trim().toLowerCase(),all=accounts();if(all[email]){$('#signupError').textContent='An account already exists for this email.';return}let user={password:$('#signupPassword').value,name:$('#signupName').value.trim(),role:$('#signupRole').value,title:$('#signupRole').value==='Manager'?'Workspace manager':'Team member'},own=JSON.parse(localStorage.getItem('workpilot-accounts')||'{}');own[email]=user;localStorage.setItem('workpilot-accounts',JSON.stringify(own));sessionStorage.setItem('workpilot-user',email);activateUser(user);toast('Your WorkPilot account is ready.')};
$('#authToggle').onclick=()=>{let signup=$('#signupForm').hidden;$('#signupForm').hidden=!signup;$('#loginForm').hidden=signup;$('#authEyebrow').textContent=signup?'CREATE ACCOUNT':'WELCOME BACK';$('#authTitle').textContent=signup?'Create your WorkPilot account':'Sign in to WorkPilot';$('#authSubtitle').textContent=signup?'Your account is saved in this browser.':'Enter your details to access your workspace.';$('#authToggle').innerHTML=signup?'Already have an account? <strong>Sign in</strong>':'New to WorkPilot? <strong>Create an account</strong>'};
$$('[data-demo]').forEach(b=>b.onclick=()=>{$('#loginEmail').value=b.dataset.demo;$('#loginPassword').value='workpilot';$('#loginError').textContent=''});$('#showPassword').onclick=function(){let i=$('#loginPassword'),show=i.type==='password';i.type=show?'text':'password';this.textContent=show?'Hide':'Show'};$('#signOut').onclick=()=>{sessionStorage.removeItem('workpilot-user');document.body.className='auth-pending';$('#loginForm').reset()};let stored=accounts()[sessionStorage.getItem('workpilot-user')];if(stored)activateUser(stored);
$$('.nav-link').forEach(a=>a.onclick=e=>{e.preventDefault();$$('.nav-link').forEach(x=>x.classList.remove('active'));a.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+a.dataset.page).classList.add('active');let n={dashboard:'Good morning, '+(currentUser?.name.split(' ')[0]||'Manasi')+' ✦',tickets:'All tickets',board:'Kanban board',team:'Team members',reports:'Reports'};$('#pageTitle').textContent=n[a.dataset.page];$('#pageEyebrow').textContent=a.dataset.page==='dashboard'?'Monday, September 8':'VERTEX CONSULTING'});$$('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-page="${b.dataset.go}"]`).click());$$('#search,#statusFilter,#priorityFilter').forEach(x=>x.addEventListener('input',renderRows));
$('#focusSearch').onclick=()=>{document.querySelector('[data-page="tickets"]').click();$('#search').focus()};$('#notifications').onclick=()=>toast('3 tickets need attention: TASK-104, TASK-098, and TASK-107.');$('#newTicket').onclick=()=>$('#modal').classList.add('open');$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};
$('#ticketForm').onsubmit=e=>{e.preventDefault();let name=$('#ticketAssignee').value,d=new Date($('#ticketDeadline').value+'T00:00:00'),today=new Date();today.setHours(0,0,0,0);let days=Math.round((d-today)/86400000),num=Math.max(...tickets.map(t=>+t.id.split('-')[1]))+1,t={id:`TASK-${num}`,title:$('#ticketTitle').value.trim(),person:name,initials:initials(name),priority:$('#ticketPriority').value,due:days===0?'Today':days===1?'Tomorrow':d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'}),date:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'}),status:'Assigned',progress:0,description:$('#ticketDescription').value.trim()};tickets.unshift(t);save();render();$('#modal').classList.remove('open');e.target.reset();toast(`${t.id} created and assigned to ${name}.`);document.querySelector('[data-page="tickets"]').click()};
$('#roleSwitch').onclick=()=>toast(`You are signed in as ${currentUser?.role||'Manager'}.`);$('#generateReport').onclick=()=>toast('Report generation is ready for the Flask/PostgreSQL version.');document.addEventListener('click',e=>{let s=e.target.closest('[data-status]')?.dataset.status,o=e.target.closest('[data-open]')?.dataset.open;if(s)advance(s);if(o){let t=tickets.find(x=>x.id===o);toast(`${t.id}: ${t.title} · ${t.status} · ${t.progress}% complete`)}});$$('.segmented button').forEach(b=>b.onclick=()=>{showingMine=b.textContent==='Mine';$$('.segmented button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderRows()});render();
