/* Management features added to the standalone WorkPilot prototype. */
let employees=JSON.parse(localStorage.getItem('workpilot-employees')||'null')||[
  {id:'emp-1',name:'Rahul Sharma',email:'rahul@vertexconsulting.com',department:'Sales'},
  {id:'emp-2',name:'Priya Patel',email:'priya@vertexconsulting.com',department:'Operations'},
  {id:'emp-3',name:'Jordan Lee',email:'jordan@vertexconsulting.com',department:'Engineering'},
  {id:'emp-4',name:'Ananya Rao',email:'ananya@vertexconsulting.com',department:'Marketing'}
];
let editingEmployeeId=null,editingTicketId=null;
const saveEmployees=()=>localStorage.setItem('workpilot-employees',JSON.stringify(employees));
function row(t){return `<tr><td><button class="ticket-link" data-open="${t.id}"><strong>${t.id}</strong><small>${t.title}</small></button></td><td><div class="assignee"><span class="avatar">${t.initials}</span>${t.person}</div></td><td><span class="priority ${t.priority}">${t.priority}</span></td><td>${t.date}<small>${t.due}</small></td><td><button class="pill ${statusClass(t.status)} status-button" data-status="${t.id}" title="Advance ticket status">${t.status}</button></td><td><span class="bar"><i style="width:${t.progress}%"></i></span>${t.progress}%</td><td><button class="more action-button" data-actions="${t.id}" aria-label="Ticket actions">•••</button></td></tr>`}
function renderTeam(){
  $('#teamList').innerHTML='<div class="team-row header-row"><span>Member</span><span>Active workload</span><span>Completed</span><span>Completion rate</span></div>'+employees.map(emp=>{let own=tickets.filter(t=>t.person===emp.name),done=own.filter(t=>t.status==='Completed').length,rate=own.length?Math.round(done/own.length*100):0;return `<div class="team-row"><div class="member"><span class="avatar">${initials(emp.name)}</span><div><strong>${emp.name}</strong><small>${emp.department} · ${emp.email}</small></div></div><span>${own.filter(t=>t.status!=='Completed').length} tickets</span><span>${done} this month</span><span class="completion">${rate}%</span><span class="employee-actions"><button data-edit-employee="${emp.id}">Edit</button><button class="danger-link" data-remove-employee="${emp.id}">Remove</button></span></div>`}).join('')||'<p class="no-results">No employees yet. Add your first team member.</p>';
}
function populateAssignees(selected){$('#ticketAssignee').innerHTML=employees.map(emp=>`<option value="${emp.name}">${emp.name}</option>`).join('');if(selected)$('#ticketAssignee').value=selected;}
function openEmployeeModal(employee){editingEmployeeId=employee?.id||null;$('#employeeModalLabel').textContent=employee?'EDIT EMPLOYEE':'ADD EMPLOYEE';$('#employeeModalTitle').textContent=employee?'Edit team member':'New team member';$('#employeeSubmit').textContent=employee?'Save changes':'Add employee';$('#employeeName').value=employee?.name||'';$('#employeeEmail').value=employee?.email||'';$('#employeeDepartment').value=employee?.department||'';$('#employeeModal').classList.add('open')}
function openTicketEditor(ticket){editingTicketId=ticket?.id||null;$('#ticketModalLabel').textContent=ticket?'EDIT TICKET':'CREATE TICKET';$('#ticketModalTitle').textContent=ticket?'Edit ticket':'New ticket';$('#ticketSubmit').textContent=ticket?'Save ticket changes':'Create ticket';populateAssignees(ticket?.person);$('#ticketTitle').value=ticket?.title||'';$('#ticketPriority').value=ticket?.priority||'High';$('#ticketDeadline').value=ticket?.deadlineISO||'';$('#ticketDescription').value=ticket?.description||'';$('#modal').classList.add('open')}
function closeTicketModal(){$('#modal').classList.remove('open');editingTicketId=null}
$('#newTicket').onclick=()=>openTicketEditor();$('#closeModal').onclick=closeTicketModal;
$('#ticketForm').onsubmit=e=>{e.preventDefault();let name=$('#ticketAssignee').value,d=new Date($('#ticketDeadline').value+'T00:00:00'),today=new Date();today.setHours(0,0,0,0);let days=Math.round((d-today)/86400000),formatted=d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'}),data={title:$('#ticketTitle').value.trim(),person:name,initials:initials(name),priority:$('#ticketPriority').value,due:days===0?'Today':days===1?'Tomorrow':formatted,date:formatted,deadlineISO:$('#ticketDeadline').value,description:$('#ticketDescription').value.trim()};if(editingTicketId){let ticket=tickets.find(t=>t.id===editingTicketId);Object.assign(ticket,data);toast(`${ticket.id} updated.`)}else{let ticket={id:`TASK-${Math.max(...tickets.map(t=>+t.id.split('-')[1]))+1}`,...data,status:'Assigned',progress:0};tickets.unshift(ticket);toast(`${ticket.id} created and assigned to ${name}.`)}save();render();closeTicketModal();document.querySelector('[data-page="tickets"]').click()};
$('#addEmployee').onclick=()=>openEmployeeModal();$('#closeEmployeeModal').onclick=()=>$('#employeeModal').classList.remove('open');$('#employeeModal').onclick=e=>{if(e.target===$('#employeeModal'))$('#employeeModal').classList.remove('open')};
$('#employeeForm').onsubmit=e=>{e.preventDefault();let data={name:$('#employeeName').value.trim(),email:$('#employeeEmail').value.trim(),department:$('#employeeDepartment').value.trim()};if(editingEmployeeId){let employee=employees.find(x=>x.id===editingEmployeeId),oldName=employee.name;Object.assign(employee,data);tickets.filter(t=>t.person===oldName).forEach(t=>{t.person=data.name;t.initials=initials(data.name)});save();toast(`${data.name}'s profile updated.`)}else{employees.push({id:'emp-'+Date.now(),...data});toast(`${data.name} added to the team.`)}saveEmployees();render();$('#employeeModal').classList.remove('open')};
function menuFor(id,button){let ticket=tickets.find(t=>t.id===id),m=$('#actionMenu'),rect=button.getBoundingClientRect();m.innerHTML=`<button data-menu-action="edit" data-ticket="${id}">✎ Edit ticket</button><button data-menu-action="submit" data-ticket="${id}">↗ Mark as submitted</button><button data-menu-action="complete" data-ticket="${id}">✓ Mark as completed</button><button class="danger-link" data-menu-action="delete" data-ticket="${id}">× Delete ticket</button>`;m.style.top=`${rect.bottom+5}px`;m.style.left=`${Math.max(12,rect.left-145)}px`;m.classList.add('show')}
document.addEventListener('click',e=>{let actionButton=e.target.closest('[data-actions]');if(actionButton){e.stopPropagation();menuFor(actionButton.dataset.actions,actionButton);return}let action=e.target.closest('[data-menu-action]');if(action){let ticket=tickets.find(t=>t.id===action.dataset.ticket);if(action.dataset.menuAction==='edit')openTicketEditor(ticket);if(action.dataset.menuAction==='submit'){ticket.status='Pending Review';ticket.progress=Math.max(ticket.progress,90);save();render();toast(`${ticket.id} submitted for review.`)}if(action.dataset.menuAction==='complete'){ticket.status='Completed';ticket.progress=100;save();render();toast(`${ticket.id} marked as completed.`)}if(action.dataset.menuAction==='delete'&&confirm(`Delete ${ticket.id}?`)){tickets=tickets.filter(t=>t.id!==ticket.id);save();render();toast(`${ticket.id} deleted.`)}$('#actionMenu').classList.remove('show');return}let edit=e.target.closest('[data-edit-employee]');if(edit){openEmployeeModal(employees.find(x=>x.id===edit.dataset.editEmployee));return}let remove=e.target.closest('[data-remove-employee]');if(remove){let employee=employees.find(x=>x.id===remove.dataset.removeEmployee);if(confirm(`Remove ${employee.name} from the team? Their tickets will remain in the system.`)){employees=employees.filter(x=>x.id!==employee.id);saveEmployees();renderTeam();toast(`${employee.name} removed from the team.`)}return}let open=e.target.closest('[data-open]');if(open){openTicketEditor(tickets.find(t=>t.id===open.dataset.open));return}if(!e.target.closest('#actionMenu'))$('#actionMenu').classList.remove('show')});
populateAssignees();render();
